---
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  kafka-ui:
    image: consdata/kouncil
    container_name: kafka-ui
    ports:
      - "80:8080"
    restart: always
    environment:
      - bootstrapServers=localhost:9092